# Generated by Django 5.1.6 on 2025-03-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=120)),
                ("password", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("date", models.DateField()),
            ],
        ),
    ]
